site_name: Investigadores Geneticos
theme:
  name: material
  language: pt-BR
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 

nav:
  - Desafio Genetico: 'game.html'
  - Cartas: 'cards.html'
  - 1. Como jogar: index.md
  - 2. Erros Inatos do Metabolismo EIM: ErroInatoMetabolismoEIM.md
  - 3. Tabela de Sintomas de MPS: tabela.md
  - 4. MC MPS e seus tipos: mcmpsetipos.md

extra_javascript:
  - https://cdn.tiny.cloud/1/2jt1cuik6ds2i08040n9c4c4igidhw9artwxbhb5q1m7e4bo/tinymce/5/tinymce.min.js  # TinyMCE script with API key
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js  # Font Awesome for icons
#  - assets/js/script.js  # Wordle game script
#  - assets/js/editor.js  # TinyMCE initialization script
  - assets/js/editor-button.js # TinyMCE custom button script
#  - assets/js/firebase.js  # Firebase script for Wordle game

extra_css:
  - assets/css/styles.css  # Custom CSS for the Wordle game

extra:
  generator: false
  
