site_name: Aquele nome lá 
theme:
  name: material
  language: pt-BR
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 

nav:
  - Jogo: '/intro.html'
  - Sobre o projeto: index.md
  - 1. Aqui:
    - 1.1. Vão seus docs:
      - 1.1.1. Organizados do jeito que quiser: CoisasdaBia.md

extra_javascript:
  - path: assets/js/editor.js  # TinyMCE initialization script
    type: module
  - path: assets/js/firebase.js  # Firebase script for Wordle game
    type: module
  - https://cdn.tiny.cloud/1/2jt1cuik6ds2i08040n9c4c4igidhw9artwxbhb5q1m7e4bo/tinymce/5/tinymce.min.js  # TinyMCE script with API key
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js  # Font Awesome for icons
  - https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js  # Firebase script
  - https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js  # Firestore script
  - https://www.gstatic.com/firebasejs/10.13.0/firebase-auth.js  # Auth script
  - assets/js/script.js  # Wordle game script
extra_css:
  - assets/css/styles.css  # Custom CSS for the Wordle game
  
